### ISSUE TITLE
Building document collections with a manifest (and replace `Makefile`)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#130]
Since https://github.com/metanorma/metanorma/issues/91 is implemented, we are able to compile the following without giving any options (as all options can be incorporated in input files):

```sh
# MN AsciiDoc
metanorma blah.adoc

# MN XML
metanorma blah.xml
```

The `Makefile` is used for batch processing of multiple Metanorma documents at once:
* Some MN documents need to be compiled from source (.adoc).
* Some MN documents are already in MN XML format, but need to generate the rendered output.

The goal of batch processing is to be able to generate a mini-site for a collection of Metanorma documents.

We can get rid of the `Makefile`, IFF we can reproduce the following functionality.

## Current `metanorma.yml`

The current `metanorma.yml` file is used to define a Metanorma document collection, how to build the Metanorma input files, and how to package them together.

There are 3 indicative build flows across our mn-sample-* repos:

* mn-samples-itu (typical)
* mn-samples-ogc (uses built_targets)
* mn-samples-ietf (uses external tools, xml2rfc)

It looks like this (from mn-samples-ogc):

```yaml
---
metanorma:
  formats: [ xml, rxl, html, doc, pdf ]
  source:
    built_targets:
      sources/00-027.xml: sources/00-027/document.adoc
      sources/18-016r1.xml: sources/18-016r1/document.adoc
      sources/18-046.xml: sources/18-046/document.adoc
      sources/18-053r2.xml: sources/18-053r2/document.adoc
relaton:
  collection:
    organization: "OGC: The Open Geospatial Consortium"
    name: "OGC Publications in Metanorma"
```

The `formats` key is used to specify the extensions to be generated for those files. 

The `built_targets` key the output file destination (key) and the input source (value). e.g. `sources/00-027.xml: sources/00-027/document.adoc` means `sources/00-027.xml` is the output file, `sources/00-027/document.adoc` is the input file. This can be handled with #134 .

If `build_targets` doesn't exist, the Makefile will look for documents under `sources/*.adoc`.

All rendered documents will be placed under `documents/*.{xml,rxl,html,pdf,doc}`.

Then the `relaton` command will be run on `documents/` to generate the final Relaton RXL file `documents.rxl` and the minisite at `documents.html`.

## Future manifest

There are some limitations right now:
* This flow is unable to handle different extensions for different flavors, e.g. ISO and CalConnect documents within the same collection -- CalConnect doesn't support DOC output.

I think a better document manifest could be like this, considering GHA syntax:

```yaml
name: Collection Name
author: Collection Author
sources:
  - 'sources/*.adoc'
  - pattern: 'sources/iso/*.adoc'
    extensions: [ doc, pdf, xml ]
  - pattern: 'sources/cc/*.adoc'
    extensions: [ pdf, xml ]
  - pattern: 'sources/ogc/**/*.adoc'
    extensions: [ pdf, xml ]
  - pattern: 'built_ogc/*.xml'
    extensions: [ pdf ]
output_dir: documents
output_rxl: documents.rxl     # <== not sure about this
output_site: documents.html  # <== not sure about this
```

The command to build this document collection would be:

```sh
metanorma compile metanorma.yml
```

This syntax can be flexible for future needs, e.g.:
* Building a transportable "Metanorma document pre-rendered package" (i.e. Metanorma document archivable)
* Building a transportable "Metanorma collection package"

Thoughts @opoudjis @abunashir ?
