### ISSUE TITLE
Collection/site generation: update docs, support wildcards and directories

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#192]
In mn-samples-itu I had to do this:

```sh
bundle exec metanorma site generate ./sources/ -c collection.yml
```

```yaml
---
metanorma:
  source:
    files:
      - source/D-REC-D.19-201003-E.adoc
      - source/G.191.adoc
      - source/G.650.1-201803.adoc
      - source/STL-manual.adoc
      - ...
  collection:
    organization: "International Telecommunications Union -- Standardization"
    name: "ITU-T Recommendations in Metanorma"
```

But, technically I could just do this if the command supported :

```yaml
---
metanorma:
  source:
    files:
      - source/*.adoc

  collection:
    organization: "International Telecommunications Union -- Standardization"
    name: "ITU-T Recommendations in Metanorma"
```

Can we implement something to this effect?

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-cli/issues/180#issuecomment-743712390_
