### ISSUE TITLE
Use `metanorma > collection > organization` instead of `metanorma > relaton > organization`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#209]
Right now site generate takes this config:

```yaml
---
metanorma:
  source:
    files:
     ...
      - nist-vassilev-acvp-iana.adoc

relaton:
  collection:
    organization: "National Institute of Standards and Technology > Computer Security Division"
    name: "Automated Cryptographic Validation Protocol"
```

But should be this instead:

```yaml
---
metanorma:
  source:
    files:
     ...
      - nist-vassilev-acvp-iana.adoc

  collection:
    organization: "National Institute of Standards and Technology > Computer Security Division"
    name: "Automated Cryptographic Validation Protocol"
```
