### ISSUE TITLE
`site generate` command conflates source files if the files have the same name

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#222]
In https://github.com/metanorma/mn-samples-jcgm , the metanorma.yml contains:
```yml
---
metanorma:
  source:
    files:
      - sources/jcgm/100-2008-en/document.adoc
      - sources/jcgm/101-2008-en/document.adoc
      - sources/jcgm/104-2009-en/document.adoc

  collection:
    organization: "JCGM"
    name: "JCGM Publications in Metanorma"
```

The sources are:
<img width="214" alt="Screen Shot 2021-01-26 at 8 01 11 AM" src="https://user-images.githubusercontent.com/11865/105780991-aad48480-5fac-11eb-9677-ae9186e11a46.png">

The resulting site is:
<img width="261" alt="Screen Shot 2021-01-26 at 8 01 26 AM" src="https://user-images.githubusercontent.com/11865/105781034-b3c55600-5fac-11eb-9b5c-29bab82fd357.png">

The generated file paths must be unique to handle this issue.
