### ISSUE TITLE
Extend collection.yml to accept Metanorma source files as entries

### ISSUE THREAD

**Issue by kwkwan** [metanorma/metanorma-cli#328]

**Comment by kwkwan** [comment]
Refer to https://github.com/metanorma/iso-10303-srl/commit/5472f9468bf0eff1d2ae2defcd18bc8a3627e891, there are several proposed changes in yaml files.

The `collection.yml` in `collection level` (root folder) will be changed from
```
manifest:
  level: collection
  title: ISO collection
  manifest:
  - level: document
    title: Document
    docref:
    - fileref: documents/<document-1>/document.xml
      identifier: <document-1>
      sectionsplit: true
    - fileref: documents/<document-2>/document.xml
      identifier: <document-2>
      sectionsplit: true
...
```
to 
```
manifest:
  level: collection
  title: STEP Resources Library (SRL)
  sectionsplit: true
  docref:
  - file: documents/<document-1>/collection.yml
  - file: documents/<document-2>/collection.yml
...
```

The `collection.yml` in `document level` (e.g. documents/document-1 folder) will be changed from
```
 manifest:
    - level: document
      title: Document
      docref:
        - fileref: document.xml
          identifier: <document-1>
          sectionsplit: true
```
to
```
  manifest:
    - level: document
      title: Document
      sectionsplit: true
      docref:
        - fileref: document.adoc
```

**Comment by kwkwan** [comment]
The goal of this change is to change the way to collect resources to build the collection.

Previously, `metanorma.yml` is pointed to a list of documents to build to collection.  Metanorma `compile` command are run to build each document, then a file named `collection.yml` is generated based on the list of documents.  Finally, metanorma `collection` command is run to build the collection based on the generated file `collection.yml`.

The proposed change is to find the resources to build the collection in `collection.yml`.  The `file` attributes in `collection.yml (collection level)` are pointed to `collection.yml (document level)` under different document folders.  When the attributes `fileref` are pointed to `.adoc` files, metanorma should `compile` them.  This will ideally make `metanorma collection` command run once to build and/or compile the resources.

As the format of `collection.yml` has been changed, metanorma collection may not able to provide backward compatibility of the previous format of `collection.yml`.   Moreover, source codes, tests and user guides in `metanorma` and/or `metanorma-cli` may be needed to update accordingly.

@ronaldtse @opoudjis If there are any concerns or suggestions, please let me know.

**Comment by kwkwan** [comment]
In order to minimize the impact of the original code, we can first create a separate function say `render_nested_collections` in `Metanorma::Collection` to handle compilation of documents and collections.  What do you think?

**Comment by ronaldtse** [comment]
The only collections used are in BSI and BIPM.

**Comment by opoudjis** [comment]
> As the format of collection.yml has been changed, metanorma collection may not able to provide backward compatibility of the previous format of collection.yml. Moreover, source codes, tests and user guides in metanorma and/or metanorma-cli may be needed to update accordingly.

You know very well that my response to you wanting to break backward compatibility is violent disagreement. There is in fact no particular need to break anything at all from what I am seeing, all of this can be handled as manifest preprocessing, and I've laid out to Koonwa in chat what that would look like.

The collection-level manifest change can be handled separately, because there is no existing support of YAML files as file references in a manifest. So if you iterate the manifest and find a file reference, sure, process it differently. This can go straight  in:

````
manifest:
  level: collection
  title: XXX
  sectionsplit: true
  docref:
  - fileref: documents/<document-1>/collection.yml
  - fileref: documents/<document-2>/collection.yml
...
````

There is no reason to change `fileref` to `file`, and you won't do that.

In my own work, I am introducing separate directives on how files will be preprocessed for ISO 10303 specific processing:

````
  docref:
  - file: documents/iso-10303-41/collection.yml
    schemas-only: true
  - file: documents/iso-10303-42/collection.yml
    schema-anchors: true
````

Those directives WILL BE IGNORED by metanorma code. They will be used in the preprocessing of Lutaml that happens out of scope of metanorma code, to determine which templates to use and how; see collection-nn.rb. 

Coming to the document-level manifest, there are three changes. Two are straight forward, one is not well thought out, and I object to it.

````
 manifest:
    - level: document
      title: Document
      sectionsplit: true
      docref:
        - fileref: document.adoc
````

* Sectionsplit has been moved from an attribute of docref to an attribute of manifest. That's not a problem, you just preprocess the manifest so that, if the manifest element has a sectionsplit attribute, you copy it to each of the docref listings under it. The same applies for other drectives such as attachment and bare.

So in https://github.com/metanorma/metanorma/blob/main/lib/metanorma/collection_manifest.rb, in both from_yaml and from_xml, you need to introduce a step at the start, before the recursive processing of manifests, to recurse it down. To take the YAML instance:

````
%w(bare sectionsplit attachment).each do |w|
  mnf[w] or next
  mnf["docref"]&.each do |dr|
     dr[w] ||= mnf[w]
  end
  mnf["manifest"]&.each do |m|
     m[w] ||= mnf[w]
  end
end
````

* fileref can point to *.adoc. As I said to you in Skype, because so much processing presupposes the XML is already there, any filerefs pointing to adoc need to trigger parsing to semantic XML early: Metanorma::Document::parse_file() already assumes that it can parse XML to find bibliographic information. I think the right place to do that parse is at the very beginning of parse_file : 

````
def parse_file(file, attachment, identifier = nil, index = true)
         # new preprocessing code
         if file.ends_in(".adoc")
            # find a way to propagate @compile from the collection class ( https://github.com/metanorma/metanorma/blob/06dd1299e817a92a8e5e11211697feed62ba1e02/lib/metanorma/collection.rb#L51 ) into the initialised Document class
            @compile.compile(file, { format: :asciidoc, extension_keys: :xml } )
            # there may be more options here, but let's not complicate things. Refer to https://github.com/metanorma/metanorma/blob/06dd1299e817a92a8e5e11211697feed62ba1e02/lib/metanorma/collection_fileprocess.rb#L12 
            file.sub!(/\.adoc$/, ".xml")
        end
        # existing code
        new(bibitem(file, attachment, identifier), file,
            { attachment: attachment, index: index })
      end
````

* The proposal is doing away with identifier. Processing is explicitly done as a hash of identifier to document, and the identifiers are invoked throughout for namespacing and lookup. This is done right at the start of manifest processing: https://github.com/metanorma/metanorma/blob/06dd1299e817a92a8e5e11211697feed62ba1e02/lib/metanorma/collection_manifest.rb#L49 

The document identifier in the manifest has to match the document identifier provided inside documents for links between documents, for bibliographic processing. That identifier is how links between documents are resolved, which is the entire point of collections.

* The only way you can skip identifiers in the manifest is if you presuppose the document is in Semantic XML (which it is only after Metanorma::Document::parse_file() is invoked), so that you can extract the bibliographic metadata (:bibdata) and then the authoritative identifier (Metanorma::CollectionRender::CollectionRenderer()  ). And that means you have to change around the entire processing ordering, so that the XML can be parsed the minute you start generating the manifest.

It is a complete waste of a week for a marginal improvement in user laziness.  The suggestion is unjustifiable, and if you insist on it, it's your problem.
