### ISSUE TITLE
Make `site generate` able to generate one index HTML for each group of collection (defined by customizable grouping rule)

### ISSUE THREAD

**Issue by ribose-jeffreylau** [metanorma/metanorma-cli#355]
## Motivation

At standards.calconnect.org, there is a need to create an index page for each Metanorma `:doctype:`.  Currently, there is no provision to do that in `metanorma-cli`.  Workarounds include using one Metanorma YAML and running `metanorma site generate` for each `:doctype:`.  However, there is no opportunity to generate a Relaton index file for all documents without using glue code (_e.g._, shell scripts, Makefile targets).

## Proposal

Allow specification of custom grouping rules in Metanorma YAML (_e.g._, group documents with the same `doctype` will be grouped into an index HTML specific to that `doctype`).

### Example

```yaml
metanorma:
  source:
    files: ...
  collections:
    group_by: doctype
  template:
    path: ...
```

See: https://github.com/CalConnect/standards.calconnect.org/issues/62

**Comment by ribose-jeffreylau** [comment]
This proposal does not address the case when some collections have no documents (_e.g._, there might be no documents assigned to certain `:doctype:`s yet), but an index page still has to be generated.

**Comment by ronaldtse** [comment]
Can the Liquid template be used to filter the documents based on doctype and docstage? i.e. Relaton supports `to_liquid` through `lutaml-model`.

**Comment by ribose-jeffreylau** [comment]
To address [this comment](https://github.com/metanorma/metanorma-cli/issues/355#issuecomment-2655408888):

> This proposal does not address the case when some collections have no documents (_e.g._, there might be no documents assigned to certain `:doctype:`s yet), but an index page still has to be generated.


## Further Proposal 1

```yaml
metanorma:
  ...
  collections:
    group_by:
      attribute: doctype
      values:  # List all doctypes of interest here
        - administrative
        - standard
        - ...
        - ...
```

The `values` array ensures all doctype-index HTMLs are generated, regardless of the number of documents belonging to that doctype.

This, however, does not address how `collection_name` is specified (which is used by Relaton for the `title` attribute).

## Further Proposal 2

`collections.group_by.values` renamed to `collections.group_by.definitions`, and now holds an array of `{ value, name }`.
`value: xxx` is the content with which to match the attribute (`doctype` here), and `name: ...` corresponds to `collection_name`.

```yaml
metanorma:
  ...
  collections:
    group_by:
      attribute: doctype
      definitions:  # List all doctypes of interest here
        - value: administrative
          name: Administrative Documents
        - value: standard
          name: Standard Documents
        - ...
        - ...
```

## Q&A

> Can the Liquid template be used to filter the documents based on doctype and docstage? i.e. Relaton supports `to_liquid` through `lutaml-model`.

Liquid templates can already filter documents by doctype, etc. But still only one index HTML will be generated.
