### ISSUE TITLE
Very annoying to tune the correct configuration script for Travis and GitLab

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#87]
The same goes for the `Makefile`, `.travis.yml` and `.gitlab-ci.yml`. Should we incorporate the workflow in these scripts into `metanorma-cli`?

Right now the `.travis.yml` file containing so many dependencies, I'd argue it is completely wrong. There should only be one command to handle all of this:

```yaml
# Auto-generated !!! Do not edit it manually
# use ci-master https://github.com/metanorma/metanorma-build-scripts
sudo: required
language: ruby
rvm:
  - 2.5.5
cache: bundler
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y curl git make ruby-bundler ruby-dev libxml2-dev libxslt-dev npm
  - travis_retry gem install bundler
  - travis_retry gem install nokogiri -v '1.8.5'
  - sudo bash -c "curl -L https://github.com/riboseinc/plantuml-install/raw/master/ubuntu.sh | bash"
  - travis_retry npm install puppeteer
env:
  global:
    - JAVA_OPTS="java.awt.headless=true"
    - PLANTUML_URL=http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
script:
  - plantuml -testdot
  - make clean all publish
```
